steps:
  # Step 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-t"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/ml/si-model:latest"
      - "."

  # Step 2: Push Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/ml/si-model:latest"

# Set Substitutions for project-specific settings
substitutions:
  _REGION: "asia-southeast2" # Set your desired region
  _PROJECT_ID: "school-impact" # Your Google Cloud Project ID

timeout: 1200s
