steps:
  # Step 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-t"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/ml/si-model:latest"
      - "."

  # Step 2: Push Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/ml/si-model:latest"

  # Step 3: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "si-model"
      - "--image"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/ml/si-model:latest"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      -"--port"
      -"8080"

# Set Substitutions for project-specific settings
substitutions:
  _REGION: "asia-southeast2" # Set your desired region
  _PROJECT_ID: "school-impact" # Your Google Cloud Project ID

timeout: 1200s
